/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cedros.evidenciau3.views;

import com.cedros.evidenciau3.SociosImpl;
import static com.cedros.evidenciau3.guiCedros.ShowJPanel;
import com.cedros.evidenciau3.interfaces.SociosInt;
import com.cedros.evidenciau3.models.Socios;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jerry
 */
public class EliminarSoc extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public EliminarSoc() {
        initComponents();
        initEstilos();
        CargarSocios();
    }
    
    public void initEstilos(){
        //bg.background = #fff;
        tituloLabel.setText("Eliminar Socio");
        tituloLabel.putClientProperty( "FlatLaf.styleClass", "h1" );
        NomTxt.putClientProperty("JTextField.placeholderText", "Nombre:");
        NomTxt.putClientProperty( "FlatLaf.styleClass", "h3" );
        ApeTxt.putClientProperty("JTextField.placeholderText", "Apellidos:");
        ApeTxt.putClientProperty( "FlatLaf.styleClass", "h3" );
    }
    
    //Vaciamos los datos en la jtable
    private void CargarSocios() {
        try {
            SociosInt socioint = new SociosImpl();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            socioint.listar("","").forEach((u) -> model.addRow(new Object[]{u.getFolioSocio(), u.getNombre(), u.getApellidos(), u.getTelefono(), u.getDomicilio(), u.getActividades(), u.getVigencia()}));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noRegistrado = new javax.swing.JOptionPane();
        bg = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        NomTxt = new javax.swing.JTextField();
        ApeTxt = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        bg.setMinimumSize(new java.awt.Dimension(1024, 650));
        bg.setPreferredSize(new java.awt.Dimension(1024, 650));

        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tituloLabel.setText("Eliminar Socios");

        btnGuardar.setText("Eliminar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Folio", "Nombre", "Apellidos", "telefono", "Domicilio", "Actividades", "Vigencia"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(NomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(ApeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // Regresar al panel princial:
        ShowJPanel(new Principal());
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Eliminar Socios:
        String nombre = NomTxt.getText();
        String lastname = ApeTxt.getText();
        
        //Instancia del objeto Socios         
        Socios socio = new Socios();
        socio.setNombre(nombre);
        socio.setApellidos(lastname);
        
        try {
            System.out.print("Entrando al Try");
            SociosInt socioint = new SociosImpl();
            socioint.Eliminar(nombre, lastname);
            
            NomTxt.setText("");
            ApeTxt.setText("");    
        }catch(Exception e){
            System.out.println(e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al tratar de eliminar el registro. \n", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApeTxt;
    private javax.swing.JTextField NomTxt;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JOptionPane noRegistrado;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
