/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cedros.evidenciau3.views;

import com.cedros.evidenciau3.SociosImpl;
import static com.cedros.evidenciau3.guiCedros.ShowJPanel;
import com.cedros.evidenciau3.interfaces.SociosInt;
import com.cedros.evidenciau3.models.Socios;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Jerry
 */
public class formRegSocio extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public formRegSocio() {
        initComponents();
        initEstilos();
        
    }
    
    public void initEstilos(){
        //bg.background = #fff;
        tituloLabel.setText("Formulario de Registro de Socios");
        tituloLabel.putClientProperty( "FlatLaf.styleClass", "h1" );
        folioTxt.putClientProperty("JTextField.placeholderText"
                                                            , "Folio de Socio:");
        telefonotxt.putClientProperty("JTextField.placeholderText"
                                                        , "Numero telefónico:");
        NomTxt.putClientProperty("JTextField.placeholderText", "Nombre:");
        ApeTxt.putClientProperty("JTextField.placeholderText", "Apellidos:");
        
        
        domtxt.putClientProperty("JTextField.placeholderText", "Domicilio:");
        acttxt.putClientProperty("JTextField.placeholderText", "Actividad");
        folioTxt.putClientProperty( "FlatLaf.styleClass", "h3" );
        telefonotxt.putClientProperty( "FlatLaf.styleClass", "h3" );
        NomTxt.putClientProperty( "FlatLaf.styleClass", "h3" );
        ApeTxt.putClientProperty( "FlatLaf.styleClass", "h3" );
        
        datetxt.putClientProperty("FlatLaf.styleClass", "h3");
        domtxt.putClientProperty("FlatLaf.styleClass", "h3");
        acttxt.putClientProperty("FlatLaf.styleClass", "h3");
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jformateado = new javax.swing.JFormattedTextField();
        bg = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        folioTxt = new javax.swing.JTextField();
        NomTxt = new javax.swing.JTextField();
        ApeTxt = new javax.swing.JTextField();
        domtxt = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        telefonotxt = new javax.swing.JTextField();
        acttxt = new javax.swing.JTextField();
        datetxt = new com.toedter.calendar.JDateChooser();

        jformateado.setEditable(false);

        bg.setMinimumSize(new java.awt.Dimension(1024, 650));
        bg.setPreferredSize(new java.awt.Dimension(1024, 650));

        tituloLabel.setText("Registro Socios");

        folioTxt.setEditable(false);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        datetxt.setForeground(new java.awt.Color(255, 255, 255));
        datetxt.setDateFormatString("MMM d, yyyy");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(domtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(folioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(267, 267, 267)
                                .addComponent(datetxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(acttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(telefonotxt)
                                        .addGap(27, 27, 27))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(NomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ApeTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)))))))
                        .addGap(162, 162, 162))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(folioTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(datetxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(domtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // Regresar al panel princial:
        ShowJPanel(new Principal());
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombre = NomTxt.getText();
        String lastname = ApeTxt.getText();
        String phone = telefonotxt.getText();
        String address = domtxt.getText();
        String leisures = acttxt.getText();
        String selectedDate = ((JTextField)datetxt.getDateEditor()
                                                  .getUiComponent()).getText();
        
        //Instancia del objeto Socios         
        Socios socio = new Socios();
        socio.setNombre(nombre);
        socio.setApellidos(lastname);
        socio.setTelefono(phone);
        socio.setDomicilio(address);
        socio.setActividades(leisures);
        socio.setVigencia(selectedDate);
        
        try {
            SociosInt socioint = new SociosImpl();
            socioint.Registrar(socio);
            JOptionPane.showMessageDialog(null, "Socio registrado con éxito",
                "REGISTRO EXITOSO", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            System.out.println(e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + "registrar" + " el socio. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        // Registra los datos del formulario de usuarios:
        //String name = NomTxt.getText();
        //String Lname = "lerma"; //ApeTxt.getText();
        //String phone = "7037844580"; //telefonotxt.getText();
        //String dom = "Siempre viva 443"; //domtxt.getText();
        //String act = "Yoga";//acttxt.getText();
        //String vig = "3/16/2024";//datetxt.getText();
        
        // Validaciones para los campos
        
        //socio.setFolioSocio(folioSocio);
        //socio.setNombre(name);
        //socio.Set<Lname> hashSet = new HashSet<Lname>();
        
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApeTxt;
    private javax.swing.JTextField NomTxt;
    private javax.swing.JTextField acttxt;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private com.toedter.calendar.JDateChooser datetxt;
    private javax.swing.JTextField domtxt;
    private javax.swing.JTextField folioTxt;
    private javax.swing.JFormattedTextField jformateado;
    private javax.swing.JTextField telefonotxt;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
