/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cedros.evidenciau3;


import com.cedros.evidenciau3.views.*;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatGradiantoNatureGreenIJTheme;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author GERARDO LERMA BAHENA
 */
public class guiCedros extends javax.swing.JFrame {

    /**
     * Creates new form guiCedros
     */
    public guiCedros() {
        //llamando a los metodos creados para darle funcionamiento a la GUI
        initComponents();
        initEstilos();
        InitContent();
        
    }
    
    private void initEstilos() {
        //com.cedros.evidenciau3.views.bg.setBackgroundColor(Color.);
    }
    
    private void InitContent() {
        //Muestra el jpanel de la imagen alusiva
        ShowJPanel(new Principal());
    }
    //Meotodo para mostrar cualquier jpanel, recibe una variable objeto jpanel
    public static void ShowJPanel(JPanel p) {
        p.setSize(1024, 650);
        p.setLocation(0,0);
        
        contenidos.removeAll();
        contenidos.add(p, BorderLayout.CENTER);
        contenidos.revalidate();
        contenidos.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenidos = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSocOpSalir = new javax.swing.JMenu();
        regMenuSoc = new javax.swing.JMenuItem();
        consulMenuSoc = new javax.swing.JMenuItem();
        delMenuSoc = new javax.swing.JMenuItem();
        salirMenuSoc = new javax.swing.JMenuItem();
        menuProveedores = new javax.swing.JMenu();
        regMenuProv = new javax.swing.JMenuItem();
        consulMenuProv = new javax.swing.JMenuItem();
        delMenuProv = new javax.swing.JMenuItem();
        backMenuProv = new javax.swing.JMenuItem();
        menuActividades = new javax.swing.JMenu();
        regMenuActividad = new javax.swing.JMenuItem();
        consulMenuActividad = new javax.swing.JMenuItem();
        delMenuActividad = new javax.swing.JMenuItem();
        backMenuActividad = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        repSocios = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        MenuSalirOp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout contenidosLayout = new javax.swing.GroupLayout(contenidos);
        contenidos.setLayout(contenidosLayout);
        contenidosLayout.setHorizontalGroup(
            contenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        contenidosLayout.setVerticalGroup(
            contenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        menuSocOpSalir.setText("Socios");

        regMenuSoc.setText("Registrar");
        regMenuSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regMenuSocActionPerformed(evt);
            }
        });
        menuSocOpSalir.add(regMenuSoc);

        consulMenuSoc.setText("Consultar");
        consulMenuSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulMenuSocActionPerformed(evt);
            }
        });
        menuSocOpSalir.add(consulMenuSoc);

        delMenuSoc.setText("Eliminar");
        delMenuSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delMenuSocActionPerformed(evt);
            }
        });
        menuSocOpSalir.add(delMenuSoc);

        salirMenuSoc.setText("Salir");
        salirMenuSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuSocActionPerformed(evt);
            }
        });
        menuSocOpSalir.add(salirMenuSoc);

        jMenuBar1.add(menuSocOpSalir);

        menuProveedores.setText("Proveedores");

        regMenuProv.setText("Registrar");
        regMenuProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regMenuProvActionPerformed(evt);
            }
        });
        menuProveedores.add(regMenuProv);

        consulMenuProv.setText("Consultar");
        consulMenuProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulMenuProvActionPerformed(evt);
            }
        });
        menuProveedores.add(consulMenuProv);

        delMenuProv.setText("Eliminar");
        delMenuProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delMenuProvActionPerformed(evt);
            }
        });
        menuProveedores.add(delMenuProv);

        backMenuProv.setText("Regresar");
        backMenuProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuProvActionPerformed(evt);
            }
        });
        menuProveedores.add(backMenuProv);

        jMenuBar1.add(menuProveedores);

        menuActividades.setText("Actividades");

        regMenuActividad.setText("Registrar");
        regMenuActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regMenuActividadActionPerformed(evt);
            }
        });
        menuActividades.add(regMenuActividad);

        consulMenuActividad.setText("Consultar");
        consulMenuActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulMenuActividadActionPerformed(evt);
            }
        });
        menuActividades.add(consulMenuActividad);

        delMenuActividad.setText("Eliminar");
        delMenuActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delMenuActividadActionPerformed(evt);
            }
        });
        menuActividades.add(delMenuActividad);

        backMenuActividad.setText("Regresar");
        backMenuActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuActividadActionPerformed(evt);
            }
        });
        menuActividades.add(backMenuActividad);

        jMenuBar1.add(menuActividades);

        menuReportes.setText("Reportes");

        repSocios.setText("Reporte Socios");
        repSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repSociosActionPerformed(evt);
            }
        });
        menuReportes.add(repSocios);

        jMenuBar1.add(menuReportes);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });

        MenuSalirOp.setText("Cerrar Sesion");
        MenuSalirOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirOpActionPerformed(evt);
            }
        });
        menuSalir.add(MenuSalirOp);

        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        //El menu de salir tiene un sub item salir donde si hay funcionalidad
    }//GEN-LAST:event_menuSalirActionPerformed

    private void MenuSalirOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirOpActionPerformed
        // funcion de salir:
        this.dispose();
    }//GEN-LAST:event_MenuSalirOpActionPerformed

    private void salirMenuSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuSocActionPerformed
        //La funcion de Salir:
        this.dispose();
    }//GEN-LAST:event_salirMenuSocActionPerformed

    private void regMenuSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regMenuSocActionPerformed
        // Mostrar el panel de Socios
        ShowJPanel(new formRegSocio());
        
    }//GEN-LAST:event_regMenuSocActionPerformed

    private void consulMenuSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulMenuSocActionPerformed
        // Mostrar el panel de consultar Socio:
        ShowJPanel(new formConsultarSocio());
    }//GEN-LAST:event_consulMenuSocActionPerformed

    private void delMenuProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delMenuProvActionPerformed
        // ir a eliminar proveedor:
        ShowJPanel(new EliminarProveedor());
    }//GEN-LAST:event_delMenuProvActionPerformed

    private void delMenuActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delMenuActividadActionPerformed
        // llamar al panel de eliminar Actividad:
        ShowJPanel(new EliminarAct());
    }//GEN-LAST:event_delMenuActividadActionPerformed

    private void delMenuSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delMenuSocActionPerformed
        // Abre el panel eliminar socio:
        ShowJPanel(new EliminarSoc());
    }//GEN-LAST:event_delMenuSocActionPerformed

    private void backMenuProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuProvActionPerformed
        // Regresar al panel principal
        ShowJPanel(new Principal());
    }//GEN-LAST:event_backMenuProvActionPerformed

    private void backMenuActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuActividadActionPerformed
        // Regresar al Panel Principal
        ShowJPanel(new Principal());
    }//GEN-LAST:event_backMenuActividadActionPerformed

    private void regMenuProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regMenuProvActionPerformed
        // Ir al panel de registro de proveedores:
        ShowJPanel(new formRegProveedor());
    }//GEN-LAST:event_regMenuProvActionPerformed

    private void consulMenuProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulMenuProvActionPerformed
        // ir a Coonsultar proveedor:
        ShowJPanel(new formConsultarProveedor());
    }//GEN-LAST:event_consulMenuProvActionPerformed

    private void regMenuActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regMenuActividadActionPerformed
        // ir al panel de registro de actividad:
        ShowJPanel(new formRegActividad());
    }//GEN-LAST:event_regMenuActividadActionPerformed

    private void consulMenuActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulMenuActividadActionPerformed
        // llamar al Panel de Consultar Actividad
        ShowJPanel(new formConsultarActividad());
    }//GEN-LAST:event_consulMenuActividadActionPerformed

    private void repSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repSociosActionPerformed
        // llamar al reporte de socios:
        ShowJPanel(new reporteSocios());
    }//GEN-LAST:event_repSociosActionPerformed

    /**
     * Nuestro main
     */
    public static void main(String args[]) {
        
        FlatGradiantoNatureGreenIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiCedros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuSalirOp;
    private javax.swing.JMenuItem backMenuActividad;
    private javax.swing.JMenuItem backMenuProv;
    private javax.swing.JMenuItem consulMenuActividad;
    private javax.swing.JMenuItem consulMenuProv;
    private javax.swing.JMenuItem consulMenuSoc;
    private static javax.swing.JPanel contenidos;
    private javax.swing.JMenuItem delMenuActividad;
    private javax.swing.JMenuItem delMenuProv;
    private javax.swing.JMenuItem delMenuSoc;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuActividades;
    private javax.swing.JMenu menuProveedores;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenu menuSocOpSalir;
    private javax.swing.JMenuItem regMenuActividad;
    private javax.swing.JMenuItem regMenuProv;
    private javax.swing.JMenuItem regMenuSoc;
    private javax.swing.JMenuItem repSocios;
    private javax.swing.JMenuItem salirMenuSoc;
    // End of variables declaration//GEN-END:variables
}
